<a href="https://colab.research.google.com/github/JLeninMChura/EJERCICIOS-DE-APLICACI-N-DE-NUMPY-JLMCH-23-04-2024/blob/main/Tarea_23_04_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importar NumPy:
import numpy as np

#***1. Creación de Arrays:***

#1.1 Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.

In [2]:
# Creamos un array de numpy con los elementos 1, 2, 3, 4, 5 y lo guardamos en la variable 'vector'
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


#1.2 Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.

In [35]:
# Creamos una matriz 3x3 de numpy con los elementos del 1 al 9 y la guardamos en la variable 'matriz'
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#1.3 Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.


In [4]:
# Creamos una matriz de numpy de 2 filas y 4 columnas, llena de ceros, y la guardamos en la variable 'matriz_ceros'
matriz_ceros = np.zeros((2, 4))
print(matriz_ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#1.4 Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.

In [5]:
## Creamos una matriz de numpy de 3 filas y 2 columnas, llena de unos, y la guardamos en la variable 'matriz_unos'
matriz_unos = np.ones((3, 2))
print(matriz_unos)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


#1.5 Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.

In [6]:
# Creamos una matriz de numpy de 4 filas y 4 columnas, llena de números enteros aleatorios entre 0 y 10, y la guardamos en la variable 'matriz_random'
matriz_random = np.random.randint(0, 10, (4, 4))
print(matriz_random)

[[2 2 6 2]
 [2 7 2 9]
 [2 8 3 5]
 [8 1 6 5]]


#**2. Acceso a Elementos:**

#2.1 Accede al tercer elemento del vector creado en el paso 1.

In [7]:
## Accedemos al tercer elemento del vector numpy 'vector' (la indexación en Python comienza en 0, por lo que el índice 2 corresponde al tercer elemento) y lo guardamos en la variable 'tercer_elemento'
tercer_elemento = vector[2]
print(tercer_elemento)

3


#2.2  Acceder al elemento en la segunda fila y segunda columna de la matriz creada en el primer paso:

In [8]:
# Accedemos al elemento en la segunda fila y segunda columna de la matriz numpy 'matriz' (la indexación en Python comienza en 0, por lo que los índices 1, 1 corresponden a la segunda fila y segunda columna) y lo guardamos en la variable 'elemento_2_2'
elemento_2_2 = matriz[1, 1]
print(elemento_2_2)

5


#**3. Propiedades de los Arrays:**

#3.1 Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 2.

In [11]:
# Utilizamos la propiedad 'ndim' para obtener el número de dimensiones de la matriz numpy 'matriz' y lo guardamos en la variable 'num_dimensiones'
num_dimensiones = matriz.ndim
print(num_dimensiones)

2


#3.2 Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.

In [10]:
## Utilizamos la propiedad 'shape' para obtener la forma de la matriz numpy 'matriz' (es decir, el número de filas y columnas) y lo guardamos en la variable 'forma'
forma = matriz.shape
print(forma)

(3, 3)


#3.3 Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 1.

In [12]:
# Utilizamos la propiedad 'size' para obtener el tamaño total de la matriz numpy 'matriz' (es decir, el número total de elementos) y lo guardamos en la variable 'tamaño_total'
tamaño_total = matriz.size
print(tamaño_total)

9


#**4. Operaciones básicas**

#4.1 Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.

In [14]:
# Creamos dos matrices 2x2 'matriz1' y 'matriz2' llenas de números aleatorios enteros entre 0 y 10 usando la función 'np.random.randint'
matriz1 = np.random.randint(0, 10, (2, 2))
matriz2 = np.random.randint(0, 10, (2, 2))

# Sumamos las dos matrices 'matriz1' y 'matriz2' y guardamos el resultado en la variable 'suma'. La suma se realiza elemento por elemento.
suma = matriz1 + matriz2
print(suma)


[[ 9 15]
 [11 18]]


#4.2 Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.

In [16]:
# Creamos una matriz 'matriz3' de 3x2 y una matriz 'matriz4' de 2x3 llenas de números aleatorios enteros entre 0 y 10 usando la función 'np.random.randint'
matriz3 = np.random.randint(0, 10, (3, 2))
matriz4 = np.random.randint(0, 10, (2, 3))

# Realizamos el producto de las matrices 'matriz3' y 'matriz4' utilizando la función 'np.dot'. Esta operación realiza un producto de matrices, no un producto elemento por elemento.
producto = np.dot(matriz3, matriz4)
print(producto)

[[48 24 36]
 [48 24 36]
 [52 48 61]]


#4.3 Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2, utilizando tanto la división por elementos como la multiplicación por la inversa.

In [40]:
# Creamos dos matrices 2x2 'matriz5' y 'matriz6' llenas de números aleatorios enteros entre 1 y 10 usando la función 'np.random.randint'. Evitamos 0 para evitar la división por cero.
matriz5 = np.random.randint(1, 10, (2, 2))  # Evitamos 0 para evitar división por cero
matriz6 = np.random.randint(1, 10, (2, 2))  # Evitamos 0 para evitar división por cero

# Realizamos la división elemento por elemento de 'matriz5' y 'matriz6' utilizando la función 'np.divide' y guardamos el resultado en la variable 'div_elementos'.
div_elementos = np.divide(matriz5, matriz6)
print(div_elementos)


# Calculamos la matriz inversa de 'matriz6' utilizando la función 'np.linalg.inv' y guardamos el resultado en la variable 'matriz6_inv'.
matriz6_inv = np.linalg.inv(matriz6)

# Realizamos el producto de las matrices 'matriz5' y 'matriz6_inv' utilizando la función 'np.dot'. Esta operación realiza un producto de matrices, no un producto elemento por elemento, y es equivalente a dividir 'matriz5' por 'matriz6'.
mult_inversa = np.dot(matriz5, matriz6_inv)
print(mult_inversa)

[[2.5        0.33333333]
 [0.66666667 0.66666667]]
[[-0.75        1.08333333]
 [ 0.          0.66666667]]


#**5. Manipulación de Arrays**

#5.1 Utiliza la función reshape() para convertir el vector creado en el paso 1 en una matriz de tamaño 1x9.

In [39]:
# Redimensionamos la matriz 'matriz' a un vector de 1x9 utilizando la función 'reshape'. Nota: La matriz original debe tener al menos 9 elementos para que esto funcione.
re = matriz.reshape(1, 9)

print(f"El vector resultante es: \n{re}")

El vector resultante es: 
[[1 2 3 4 5 6 7 8 9]]


#5.2 Utiliza la función flatten() para convertir la matriz creada en el paso 2 en un vector unidimensional.

In [21]:
# Aplanamos la matriz 'matriz' a un vector unidimensional utilizando la función 'flatten'. Esta función devuelve una copia de la matriz original, aplanada a un vector.
vector_flattened = matriz.flatten()

print(vector_flattened)

[1 2 3 4 5 6 7 8 9]


#**6. Operaciones Estadísticas:**

#6.1 Calcula la suma de todos los elementos de la matriz creada en el paso 2.

In [ ]:
# Calculamos la suma total de todos los elementos en la matriz 'matriz' utilizando la función 'sum' de numpy. Esta función suma todos los elementos en el array.
suma_total = np.sum(matriz)

print(f"La suma de todos los elementos de la matriz es {suma_total}")

#6.2 Calcula la media de cada fila de la matriz creada en el paso 2.

In [24]:
# Calculamos la media de cada fila en la matriz 'matriz' utilizando la función 'mean' de numpy y especificando 'axis=1'. 'axis=1' indica que la operación se debe realizar a lo largo de las filas.
media_filas = np.mean(matriz, axis=1)

print(f"La media de cada fila de la matriz es {media_filas}")

La media de cada fila de la matriz es [2. 5. 8.]


#**7. Indexación y Rebanado:**

#7.1 Imprime la primera fila de la matriz creada en el paso 1.

In [25]:
# Extraemos la primera fila de la matriz 'matriz' utilizando la indexación de arrays de numpy. '0' se refiere a la primera fila.
primera_fila = matriz[0]

print(f"La primera fila de la matriz es {primera_fila}")

La primera fila de la matriz es [1 2 3]


#7.2 Imprime las primeras dos columnas de la matriz creada en el paso 2

In [26]:
# Extraemos las primeras dos columnas de la matriz 'matriz' utilizando la indexación de arrays de numpy. ':, :2' se refiere a todas las filas (el primer ':') y las dos primeras columnas (el ':2').
primeras_dos_columnas = matriz[:, :2]

print(f"Las primeras dos columnas de la matriz son \n{primeras_dos_columnas}")

Las primeras dos columnas de la matriz son 
[[1 2]
 [4 5]
 [7 8]]


#**8. Ejercicio Adicional**

#8.1 Define una matriz de tamaño 4x4 con valores aleatorios.

In [28]:
# Creamos una matriz 4x4 con valores aleatorios utilizando la función 'rand' de numpy. Esta función genera valores aleatorios en el rango [0, 1).
matriz = np.random.rand(4, 4)

print(f"Matriz 4x4 con valores aleatorios: \n{matriz}\n")

Matriz 4x4 con valores aleatorios: 
[[0.0070698  0.991783   0.58867935 0.55526394]
 [0.05753827 0.40102094 0.6308819  0.20570628]
 [0.49060465 0.44537513 0.71199514 0.18634218]
 [0.54331878 0.20765686 0.52055024 0.72653803]]



#8.2  Encuentra el valor máximo y su posición

In [29]:
# Utilizamos la función 'max' de numpy para obtener el valor máximo de la matriz.
valor_maximo = np.max(matriz)

# Utilizamos la función 'argmax' de numpy para obtener el índice del valor máximo en la matriz aplanada, y luego 'unravel_index' para convertir ese índice a la forma de la matriz original.
posicion_maximo = np.unravel_index(np.argmax(matriz), matriz.shape)

print(f"El valor máximo es {valor_maximo} y su posición es {posicion_maximo}\n")

El valor máximo es 0.991782999088573 y su posición es (0, 1)



#8.3  Encuentra el valor mínimo y su posición

In [30]:
# Utilizamos la función 'min' de numpy para obtener el valor mínimo de la matriz.
valor_minimo = np.min(matriz)

# Utilizamos la función 'argmin' de numpy para obtener el índice del valor mínimo en la matriz aplanada, y luego 'unravel_index' para convertir ese índice a la forma de la matriz original.
posicion_minimo = np.unravel_index(np.argmin(matriz), matriz.shape)

print(f"El valor mínimo es {valor_minimo} y su posición es {posicion_minimo}")

El valor mínimo es 0.00706980225010867 y su posición es (0, 0)
